export type {
  Address,
  Bytes32,
  Hex,
  Afterimage,
  AfterimageEvent,
  Evidence,
  WitnessConfirmation,
  WitnessReputation,
  Dispute,
  OwnershipTransfer,
  CanonicalMetadata,
} from "./types.js";

export {
  AfterimageStatus,
  EventType,
  EvidenceType,
  DisputeState,
  AFTERIMAGE_STATUS_NAMES,
  EVENT_TYPE_NAMES,
  DISPUTE_STATE_NAMES,
} from "./types.js";

export type {
  CreateAfterimageRequest,
  CreateAfterimageResponse,
  RecordObservationRequest,
  CreateEventRequest,
  CreateEventResponse,
  RegisterEvidenceRequest,
  RegisterEvidenceResponse,
  ConfirmEventRequest,
  ConfirmEventResponse,
  CreateDisputeRequest,
  CreateDisputeResponse,
  ResolveDisputeRequest,
  TransferOwnershipRequest,
  GetAfterimageResponse,
  GetEventResponse,
  ListEventsResponse,
  GetEvidenceResponse,
  GetWitnessReputationResponse,
  ListConfirmationsResponse,
  GetDisputeResponse,
  OwnershipHistoryResponse,
  ApiError,
  PaginatedQuery,
  PaginatedResponse,
  AfterimageFilter,
  DisputeFilter,
} from "./api.js";
